Package.describe({
  name: 'm:lib-models',
  version: '0.0.1',
  summary: 'Mitolojix models, hooks, publications and collection crons'
});

Package.onUse(function(api) {

  api.versionsFrom('1.0');

  api.use('m:lib-core@0.0.1');
  api.use('m:lib-accounts@0.0.1');
  api.use('m:lib-enums@0.0.1');
  api.use('m:lib-collate@0.0.1');
  api.use('m:lib-utils@0.0.1');
  api.use('m:lib-collections@0.0.1');
  api.use('m:lib-tckimlik@0.0.1');

  const assets = [
    '_privateAssets/yardimDokumani/mitolojix-brosuru.pdf',
    '_privateAssets/karakter/erkek/1.png',
    '_privateAssets/karakter/erkek/2.png',
    '_privateAssets/karakter/erkek/3.png',
    '_privateAssets/karakter/erkek/4.png',
    '_privateAssets/karakter/erkek/5.png',
    '_privateAssets/karakter/erkek/6.png',
    '_privateAssets/karakter/erkek/7.png',
    '_privateAssets/karakter/erkek/8.png',
    '_privateAssets/karakter/erkek/9.png',
    '_privateAssets/karakter/erkek/10.png',
    '_privateAssets/karakter/kadin/1.png',
    '_privateAssets/karakter/kadin/2.png',
    '_privateAssets/karakter/kadin/3.png',
    '_privateAssets/karakter/kadin/4.png',
    '_privateAssets/karakter/kadin/5.png',
    '_privateAssets/karakter/kadin/6.png',
    '_privateAssets/karakter/kadin/7.png',
    '_privateAssets/karakter/kadin/8.png',
    '_privateAssets/karakter/kadin/9.png',
    '_privateAssets/karakter/kadin/10.png',
    '_privateAssets/muhur/grup/ates-aktif.png',
    '_privateAssets/muhur/grup/ates-gorsel.png',
    '_privateAssets/muhur/grup/ates-pasif.png',
    '_privateAssets/muhur/grup/hava-aktif.png',
    '_privateAssets/muhur/grup/hava-gorsel.png',
    '_privateAssets/muhur/grup/hava-pasif.png',
    '_privateAssets/muhur/grup/saman-aktif.png',
    '_privateAssets/muhur/grup/saman-gorsel.png',
    '_privateAssets/muhur/grup/saman-pasif.png',
    '_privateAssets/muhur/grup/su-aktif.png',
    '_privateAssets/muhur/grup/su-gorsel.png',
    '_privateAssets/muhur/grup/su-pasif.png',
    '_privateAssets/muhur/grup/toprak-aktif.png',
    '_privateAssets/muhur/grup/toprak-gorsel.png',
    '_privateAssets/muhur/grup/toprak-pasif.png',
    '_privateAssets/muhur/altin/ates/akrep.png',
    '_privateAssets/muhur/altin/ates/anka.png',
    '_privateAssets/muhur/altin/ates/ari.png',
    '_privateAssets/muhur/altin/ates/cingirakli-yilan.png',
    '_privateAssets/muhur/altin/ates/ejder.png',
    '_privateAssets/muhur/altin/ates/kertenkele.png',
    '_privateAssets/muhur/altin/ates/kobra.png',
    '_privateAssets/muhur/altin/ates/kurbaga.png',
    '_privateAssets/muhur/altin/ates/orumcek.png',
    '_privateAssets/muhur/altin/ates/yarasa.png',
    '_privateAssets/muhur/gumus/ates/akrep.png',
    '_privateAssets/muhur/gumus/ates/anka.png',
    '_privateAssets/muhur/gumus/ates/ari.png',
    '_privateAssets/muhur/gumus/ates/cingirakli-yilan.png',
    '_privateAssets/muhur/gumus/ates/ejder.png',
    '_privateAssets/muhur/gumus/ates/kertenkele.png',
    '_privateAssets/muhur/gumus/ates/kobra.png',
    '_privateAssets/muhur/gumus/ates/kurbaga.png',
    '_privateAssets/muhur/gumus/ates/orumcek.png',
    '_privateAssets/muhur/gumus/ates/yarasa.png',
    '_privateAssets/muhur/altin/hava/akbaba.png',
    '_privateAssets/muhur/altin/hava/atmaca.png',
    '_privateAssets/muhur/altin/hava/baykus.png',
    '_privateAssets/muhur/altin/hava/guvercin.png',
    '_privateAssets/muhur/altin/hava/kanarya.png',
    '_privateAssets/muhur/altin/hava/karga.png',
    '_privateAssets/muhur/altin/hava/kartal.png',
    '_privateAssets/muhur/altin/hava/kirlangic.png',
    '_privateAssets/muhur/altin/hava/leylek.png',
    '_privateAssets/muhur/altin/hava/pelikan.png',
    '_privateAssets/muhur/gumus/hava/akbaba.png',
    '_privateAssets/muhur/gumus/hava/atmaca.png',
    '_privateAssets/muhur/gumus/hava/baykus.png',
    '_privateAssets/muhur/gumus/hava/guvercin.png',
    '_privateAssets/muhur/gumus/hava/kanarya.png',
    '_privateAssets/muhur/gumus/hava/karga.png',
    '_privateAssets/muhur/gumus/hava/kartal.png',
    '_privateAssets/muhur/gumus/hava/kirlangic.png',
    '_privateAssets/muhur/gumus/hava/leylek.png',
    '_privateAssets/muhur/gumus/hava/pelikan.png',
    '_privateAssets/muhur/altin/saman/aslan.png',
    '_privateAssets/muhur/altin/saman/at.png',
    '_privateAssets/muhur/altin/saman/ayi.png',
    '_privateAssets/muhur/altin/saman/deve.png',
    '_privateAssets/muhur/altin/saman/geyik.png',
    '_privateAssets/muhur/altin/saman/kaplumbaga.png',
    '_privateAssets/muhur/altin/saman/kirpi.png',
    '_privateAssets/muhur/altin/saman/kurt.png',
    '_privateAssets/muhur/altin/saman/tavsan.png',
    '_privateAssets/muhur/altin/saman/tilki.png',
    '_privateAssets/muhur/gumus/saman/aslan.png',
    '_privateAssets/muhur/gumus/saman/at.png',
    '_privateAssets/muhur/gumus/saman/ayi.png',
    '_privateAssets/muhur/gumus/saman/deve.png',
    '_privateAssets/muhur/gumus/saman/geyik.png',
    '_privateAssets/muhur/gumus/saman/kaplumbaga.png',
    '_privateAssets/muhur/gumus/saman/kirpi.png',
    '_privateAssets/muhur/gumus/saman/kurt.png',
    '_privateAssets/muhur/gumus/saman/tavsan.png',
    '_privateAssets/muhur/gumus/saman/tilki.png',
    '_privateAssets/muhur/altin/su/ahtapot.png',
    '_privateAssets/muhur/altin/su/denizati.png',
    '_privateAssets/muhur/altin/su/istakoz.png',
    '_privateAssets/muhur/altin/su/kilicbaligi.png',
    '_privateAssets/muhur/altin/su/kopekbaligi.png',
    '_privateAssets/muhur/altin/su/mors.png',
    '_privateAssets/muhur/altin/su/pirana.png',
    '_privateAssets/muhur/altin/su/vatoz.png',
    '_privateAssets/muhur/altin/su/yengec.png',
    '_privateAssets/muhur/altin/su/yunus.png',
    '_privateAssets/muhur/gumus/su/ahtapot.png',
    '_privateAssets/muhur/gumus/su/denizati.png',
    '_privateAssets/muhur/gumus/su/istakoz.png',
    '_privateAssets/muhur/gumus/su/kilicbaligi.png',
    '_privateAssets/muhur/gumus/su/kopekbaligi.png',
    '_privateAssets/muhur/gumus/su/mors.png',
    '_privateAssets/muhur/gumus/su/pirana.png',
    '_privateAssets/muhur/gumus/su/vatoz.png',
    '_privateAssets/muhur/gumus/su/yengec.png',
    '_privateAssets/muhur/gumus/su/yunus.png',
    '_privateAssets/muhur/altin/toprak/armut.png',
    '_privateAssets/muhur/altin/toprak/cam.png',
    '_privateAssets/muhur/altin/toprak/elma.png',
    '_privateAssets/muhur/altin/toprak/gurgen.png',
    '_privateAssets/muhur/altin/toprak/kavak.png',
    '_privateAssets/muhur/altin/toprak/kiraz.png',
    '_privateAssets/muhur/altin/toprak/kozalak.png',
    '_privateAssets/muhur/altin/toprak/mese.png',
    '_privateAssets/muhur/altin/toprak/sedir.png',
    '_privateAssets/muhur/altin/toprak/sogut.png',
    '_privateAssets/muhur/gumus/toprak/armut.png',
    '_privateAssets/muhur/gumus/toprak/cam.png',
    '_privateAssets/muhur/gumus/toprak/elma.png',
    '_privateAssets/muhur/gumus/toprak/gurgen.png',
    '_privateAssets/muhur/gumus/toprak/kavak.png',
    '_privateAssets/muhur/gumus/toprak/kiraz.png',
    '_privateAssets/muhur/gumus/toprak/kozalak.png',
    '_privateAssets/muhur/gumus/toprak/mese.png',
    '_privateAssets/muhur/gumus/toprak/sedir.png',
    '_privateAssets/muhur/gumus/toprak/sogut.png'
  ];
  api.addAssets(assets, 'server');

  api.addFiles('accounts/common/model.js');
  api.addFiles('accounts/server/search.js','server');
  api.addFiles('accounts/server/fixture.js','server');
  api.addFiles('accounts/server/hooks.js','server');
  api.addFiles('accounts/server/publish.js','server');
  api.addFiles('adresMaster/common/model.js');
  api.addFiles('adresMaster/server/fixture.js','server');
  api.addFiles('adresMaster/server/publish.js','server');
  api.addFiles('aktifEgitimYili/common/model.js');
  api.addFiles('aktifEgitimYili/server/fixture.js','server');
  api.addFiles('aktifEgitimYili/server/publish.js','server');
  api.addFiles('comment/common/model.js');
  api.addFiles('comment/server/hooks.js','server');
  // |--> Load order due to ders's dependency on gridfs
  api.addFiles('gridfs/common/model.js');
  api.addFiles('gridfs/server/permission.js','server');
  api.addFiles('gridfs/server/publish.js','server');
  // Load order due to ders's dependency on gridfs <--|
  api.addFiles('ders/common/model.js');
  api.addFiles('ders/server/hooks.js','server');
  api.addFiles('ders/server/publish.js','server');
  api.addFiles('giris/common/storiesModel.js');
  api.addFiles('giris/server/cron.js','server');
  api.addFiles('giris/server/publish.js','server');
  api.addFiles('karakter/common/model.js');
  api.addFiles('karakter/server/fixture.js','server');
  api.addFiles('karakter/server/hooks.js','server');
  api.addFiles('karakter/server/publish.js','server');
  api.addFiles('kurum/common/model.js');
  api.addFiles('kurum/server/search.js','server');
  api.addFiles('kurum/server/hooks.js','server');
  api.addFiles('kurum/server/publish.js','server');
  api.addFiles('mufredat/common/model.js');
  api.addFiles('mufredat/server/search.js','server');
  api.addFiles('mufredat/server/hooks.js','server');
  api.addFiles('mufredat/server/publish.js','server');
  api.addFiles('muhur/common/model.js');
  api.addFiles('muhur/server/search.js','server');
  api.addFiles('muhur/server/fixture.js','server');
  api.addFiles('muhur/server/hooks.js','server');
  api.addFiles('muhur/server/publish.js','server');
  api.addFiles('notification/common/model.js');
  api.addFiles('notification/server/cron.js','server');
  api.addFiles('notification/server/publish.js','server');
  api.addFiles('sinav/common/model.js');
  api.addFiles('sinav/server/search.js','server');
  api.addFiles('sinav/server/cron.js','server');
  api.addFiles('sinav/server/hooks.js','server');
  api.addFiles('sinav/server/publish.js','server');
  api.addFiles('sinavKagidi/common/model.js');
  api.addFiles('sinavKagidi/server/methods.js','server');
  api.addFiles('sinavKagidi/server/publish.js','server');
  api.addFiles('soru/common/model.js');
  api.addFiles('soru/server/search.js','server');
  api.addFiles('soru/server/hooks.js','server');
  api.addFiles('soru/server/publish.js','server');
  api.addFiles('soruFavori/common/model.js');
  api.addFiles('soruFavori/server/search.js','server');
  api.addFiles('soruFavori/server/publish.js','server');
  api.addFiles('soruSepeti/common/model.js');
  api.addFiles('soruSepeti/server/search.js','server');
  api.addFiles('soruSepeti/server/publish.js','server');
  api.addFiles('yardimDokumani/common/model.js');
  api.addFiles('yardimDokumani/server/fixture.js','server');
  api.addFiles('yardimDokumani/server/hooks.js','server');
  api.addFiles('yardimDokumani/server/publish.js','server');
  api.addFiles('reports.js','server');

});
